### ISSUE TITLE
launch checklist

### ISSUE THREAD

**Issue by kasumi-1** [dogmoneyswap/dogmoneyswap-interface#1]
- [x] prepare farm TVL calculation strategy to use dogmoney/usdc pair and wdoge/usdc strategy

- [x] bridge sufficient usdc, dai, usdt

- [x] collect projects/farm allocations

- [x] get token icons finalized

- [x] finish documentation updates

- [x] create socials (twitter, tg, discord?, medium)

- [x] prepare launch announcement

---

- [x] redeploy contracts

- [x] update sdk

- [x] update token list

- [x] create and add pairs 

- [x] create initial farm

- [x] farm to get dogmoney to create dogmoney pairs and more farms

- [ ] publish announcement
